name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 3 * * *'  # Runs daily at 03:15 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Make a change and commit (abc@mail.com)
        run: |
          echo "Last run: $(date -u)" > daily-run.log
          git config user.name "GitHub Actions"
          git config user.email "abc@mail.com"
          git add daily-run.log
          git commit -m "Daily commit - $(date -u)"
          git push
