name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 3 * * *'  # Runs daily at 03:15 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Make a change and commit (23f2003403@ds.study.iitm.ac.in)
        run: |
          git config user.name "GitHub Actions"
          echo user.email "23f2003403@ds.study.iitm.ac.in"
